<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#071321">
  <title>Centro de misión | Cris</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Montserrat:wght@500;600;700;800&display=swap" rel="stylesheet">
  <style>
    *{box-sizing:border-box}body{margin:0;background:#071321;color:#eaf7ff;font-family:Montserrat,sans-serif}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:max(24px,env(safe-area-inset-top)) max(5%,env(safe-area-inset-right)) 24px max(5%,env(safe-area-inset-left));border-bottom:1px solid #24587b;background:#091b2c}.top h1{margin:0;color:#ed2031;font:2.5rem Bangers,sans-serif;letter-spacing:.06em;text-shadow:2px 2px #fff}.top button{min-height:44px;padding:10px 14px;border:1px solid #6389a3;background:transparent;color:#d8edf7;cursor:pointer;font-weight:800}.wrap{width:min(1180px,90%);margin:38px auto}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:28px}.stat{padding:22px;border:1px solid #24587b;background:#0b2136;box-shadow:4px 4px #ed2031}.stat b{display:block;color:#fff;font:2.4rem Bangers,sans-serif}.stat span{color:#86b7d3;font-size:.65rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.table-wrap{max-width:100%;overflow:auto;border:1px solid #24587b;-webkit-overflow-scrolling:touch}table{width:100%;min-width:570px;border-collapse:collapse;background:#0a1c2d;font-size:.76rem}th,td{padding:14px;text-align:left;border-bottom:1px solid #173b54;vertical-align:top}th{color:#86cfee;background:#0d2940;font-size:.62rem;letter-spacing:.09em;text-transform:uppercase}.yes{color:#7de1a5;font-weight:800}.no{color:#ff8993;font-weight:800}a{color:#7ed8ff}.empty{padding:40px;text-align:center;color:#8eb2c6}.pagination{margin-top:22px;color:#fff;overflow:auto}.pagination nav>div:first-child{display:none}.pagination nav>div:last-child>div:first-child{display:none}.pagination svg{width:18px}.pagination a,.pagination span{display:inline-flex;padding:8px 11px;border:1px solid #24587b;text-decoration:none}.pagination span[aria-current="page"] span{background:#ed2031}@media(max-width:700px){.top{align-items:flex-start;padding-left:4%;padding-right:4%}.top h1{font-size:1.75rem;line-height:.9}.top button{padding:8px 10px;font-size:.6rem}.stats{grid-template-columns:1fr 1fr;gap:10px}.stat{padding:16px}.stat:last-child{grid-column:1/-1}.wrap{width:92%;margin-top:22px}th,td{padding:11px}.hide-mobile{display:none}table{min-width:460px}.pagination{padding-bottom:max(16px,env(safe-area-inset-bottom))}}@media(max-width:360px){.top{gap:10px}.top h1{font-size:1.5rem}.stats{grid-template-columns:1fr}.stat:last-child{grid-column:auto}}
  </style>
</head>
<body><header class="top"><h1>CENTRO DE MISIÓN · CRIS</h1><form method="POST" action="{{ route('rsvp.logout') }}">@csrf<button type="submit">CERRAR SISTEMA</button></form></header><main class="wrap"><section class="stats"><article class="stat"><b>{{ $confirmedHosts }}</b><span>Héroes confirmados</span></article><article class="stat"><b>{{ $confirmedGuests }}</b><span>Acompañantes</span></article><article class="stat"><b>{{ $confirmedHosts + $confirmedGuests }}</b><span>Personas en la misión</span></article></section><section class="table-wrap">@if($rsvps->isEmpty())<div class="empty">Aún no hay transmisiones recibidas.</div>@else<table><thead><tr><th>Fecha</th><th>Nombre</th><th>Respuesta</th><th>Acomp.</th><th>Teléfono</th><th class="hide-mobile">Mensaje</th></tr></thead><tbody>@foreach($rsvps as $rsvp)<tr><td>{{ $rsvp->created_at->format('d/m/Y H:i') }}</td><td><strong>{{ $rsvp->name }}</strong></td><td class="{{ $rsvp->attending ? 'yes' : 'no' }}">{{ $rsvp->attending ? 'Asistirá' : 'No asistirá' }}</td><td>{{ $rsvp->attending ? $rsvp->guests : '—' }}</td><td>{{ $rsvp->phone ?: '—' }}</td><td class="hide-mobile">{{ $rsvp->message ?: '—' }}</td></tr>@endforeach</tbody></table>@endif</section><div class="pagination">{{ $rsvps->links() }}</div></main></body>
</html>
